name: CI for VaultCourier

on:
  push:
    branches:
      - main  # Jalankan workflow saat ada push ke branch `main`
  pull_request:
    branches:
      - main  # Jalankan workflow saat ada PR ke branch `main`

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Beri izin eksekusi pada vaultcourier.sh
      - name: Make vaultcourier.sh executable
        run: chmod +x vaultcourier.sh

      # Step 3: Jalankan installer vaultcourier.sh
      - name: Run installation script
        run: ./vaultcourier.sh

      # Step 4: Save konfigurasi alias
      - name: Source shell configuration
        run: |
          if [ -n "$ZSH_VERSION" ]; then
            source ~/.zshrc
          else
            source ~/.bashrc
          fi

      # Step 5: Buat folder testfolder untuk pengujian
      - name: Create test folder
        run: |
          mkdir -p testfolder
          echo "Dummy file for testing" > testfolder/dummy.txt

      # Step 6: Test pengiriman file
      - name: Test file upload
        run: vc -f testfolder/dummy.txt
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      # Step 7: Test pengiriman folder
      - name: Test folder upload
        run: vc -d testfolder
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
