name: CI for VaultCourier

on:
  push:
    branches:
      - main  # Workflow jalan saat ada push ke branch `main`
  pull_request:
    branches:
      - main  # Workflow juga jalan saat ada PR ke branch `main`

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Python Environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r vc/requirements.txt

      # Step 4: Linting
      - name: Run Linter
        run: |
          pip install flake8
          flake8 vc/vc.py

      # Step 5: Run VaultCourier Script
      - name: Run VaultCourier
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Running VaultCourier locally..."
          python vc/vc.py --help

      # Step 6: Dummy Test (Opsional)
      - name: Dummy Test
        run: |
          echo "Testing completed!"
